config/routes.rb
Rails.application.routes.draw do
  get "borrow_requests/new"
  get "borrow_requests/create"
  get "comments/create"
  get "authors/index"
  get "authors/show"
  get "categories/index"
  get "categories/show"
  get "books/show"
  get "users/show"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home/index"
  get "signup", to: "registrations#new", as: "signup"
  post "registrations", to: "registrations#create"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"
  root "home#index"

  resources :users, only: %i(show)
  resources :books, only: %i(show)
  resources :categories, only: %i(index show)
  resources :authors, only: %i(index show)
  resources :books do
    resources :comments, only: %i(create)
    resources :borrow_requests, only: %i(new create)
  end
  resources :users do
    member do
      get "borrow_history"
    end
  end
  resources :borrow_requests, only: %i(destroy)
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true

  scope :search_by_name, lambda {|name|
                           where("name LIKE ?", "%#{name}%") if name.present?
                         }
  scope :order_by_name_asc, ->{order(name: :asc)}
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.search_by_name(params[:name]).order_by_name_asc
  end

  def show
    @author = Author.find_by(id: params[:id])
    if @author
      @books = @author.books
    else
      redirect_to authors_path, alert: t("controller.author_notfound")
    end
  end
end

app/views/authors/index.html.erb
<h1>Authors</h1>

<%= form_with url: authors_path, method: :get, local: true do %>
  <%= label_tag :name, "Search by name:" %>
  <%= text_field_tag :name, params[:name] %>
  <%= submit_tag "Search" %>
<% end %>

<ul>
  <% if @authors.present? %>
    <% @authors.each do |author| %>
      <li>- <%= link_to author.name, author_path(author) %></li>
    <% end %>
  <% else %>
    <li>No authors found</li>
  <% end %>
</ul>

app/views/authors/show.html.erb
<div class="author">
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-3">
        <div class="card">
          <div class="card-body-img">
            <img src="<%= @author.profile_picture_url %>" class="card-img-top" alt="<%= @author.name %>">
          </div>
          <div style="display: flex; flex-direction: column;">
            <p class="birth"><%= @author.name %></p>
            <p class="birth"><%= @author.birth_year %></p>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        <div class="card">
          <div class="card-body text">
            <h5 class="card-title">Tác giả: <strong><%= @author.name %></strong></h5>
            <div class="text_author">
              <p class="card-text"><%= simple_format(@author.bio) %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-10">
        <h2 class="mb-4">Những tác phẩm chính</h2>
        <ul class="list-group">
          <% @books.each do |book| %>
            <li class="list-group-item">
              <%= link_to book.name, book_path(book), class: 'btn btn-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>