config/routes.rb
Rails.application.routes.draw do
  get "borrow_requests/new"
  get "borrow_requests/create"
  get "comments/create"
  get "authors/index"
  get "authors/show"
  get "categories/index"
  get "categories/show"
  get "books/show"
  get "users/show"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home/index"
  get "signup", to: "registrations#new", as: "signup"
  post "registrations", to: "registrations#create"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"
  root "home#index"

  resources :users, only: %i(show)
  resources :books, only: %i(show)
  resources :categories, only: %i(index show)
  resources :authors, only: %i(index show)
  resources :books do
    resources :comments, only: %i(create)
    resources :borrow_requests, only: %i(new create)
  end
  resources :users do
    member do
      get "borrow_history"
    end
  end
  resources :borrow_requests, only: %i(destroy)
end

app/models/user.rb
class User < ApplicationRecord
  has_many :borrow_requests, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_secure_password

  validates :email, presence: true, length: {maximum: Settings.digit_255},
                    format: {with: Regexp.new(Settings.VALID_EMAIL_REGEX)},
                     uniqueness: true
  validates :name, presence: true,
    length: {in: 1..50, too_long: "50 characters is the maximum allowed",
             too_short: "1 character is the minimum allowed"}
  validates :password, presence: true, length: {minimum: Settings.digit_6},
                                       allow_nil: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i(show)
  before_action :set_user, only: %i(borrow_history)

  def show
    @user = User.find_by(id: params[:id])
  end

  def borrow_history
    @borrow_requests = @user.borrow_requests.order(created_at: :desc)
  end

  private
  def logged_in_user
    return if logged_in?

    flash[:danger] = t("controller.require_login")
    redirect_to login_url
  end

  def set_user
    @user = current_user
  end
end

app/views/users/borrow_history.html.erb
<div class="container mt-4">
  <h1 style="text-align: center;">Lịch sử mượn sách</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Tên sách</th>
        <th>Giá</th>
        <th>Ngày bắt đầu mượn</th>
        <th>Ngày trả</th>
        <th>Trạng thái</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @borrow_requests.each do |request| %>
        <tr>
          <td><%= link_to request.book.name, book_path(request.book) %></td>
          <td><%= request.book.price %>$</td>
          <td><%= request.start_date.strftime('%d-%m-%Y') %></td>
          <td><%= request.end_date.strftime('%d-%m-%Y') %></td>
          <td>
            <% case request.status %>
            <% when 'pending' %>
              Đang chờ xác nhận
            <% when 'borrowing' %>
              Đang mượn
            <% when 'payed' %>
              Đã trả
            <% end %>
          </td>
          <td>
            <% if request.status? %>

              <%= link_to 'Hủy yêu cầu', borrow_request_path(request), class: 'btn btn-danger delete-request'%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<h1>Thông tin người dùng</h1>
  <ul>
    <li class="nav-item"; style="list-style-type: none;">
      <%= link_to 'Lịch sử mượn sách', borrow_history_user_path(current_user),  class: 'btn btn-primary' %>
    </li>
  </ul>