config/routes.rb
Rails.application.routes.draw do
  get "borrow_requests/new"
  get "borrow_requests/create"
  get "comments/create"
  get "authors/index"
  get "authors/show"
  get "categories/index"
  get "categories/show"
  get "books/show"
  get "users/show"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home/index"
  get "signup", to: "registrations#new", as: "signup"
  post "registrations", to: "registrations#create"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"
  root "home#index"

  resources :users, only: %i(show)
  resources :books, only: %i(show)
  resources :categories, only: %i(index show)
  resources :authors, only: %i(index show)
  resources :books do
    resources :comments, only: %i(create)
    resources :borrow_requests, only: %i(new create)
  end
  resources :users do
    member do
      get "borrow_history"
    end
  end
  resources :borrow_requests, only: %i(destroy)
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true

  scope :search_by_name, lambda {|name|
                           where("name LIKE ?", "%#{name}%") if name.present?
                         }
  scope :order_by_name_asc, ->{order(name: :asc)}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.search_by_name(params[:name]).order_by_name_asc
  end

  def show
    @category = Category.find_by(id: params[:id])
    if @category
      @books = @category.books
    else
      redirect_to categories_path, alert: t("controller.categories_notfound")
    end
  end
end

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= form_with url: categories_path, method: :get, local: true do %>
  <%= label_tag :name, "Search by name:" %>
  <%= text_field_tag :name, params[:name] %>
  <%= submit_tag "Search" %>
<% end %>

<ul>
  <% if @categories.present? %>
    <% @categories.each do |category| %>
      <li>- <%= link_to category.name, category_path(category) %></li>
    <% end %>
  <% else %>
    <li>No categories found</li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1>Categories: <%= @category.name %></h1>

<ul>
  <% if @books.present? %>
    <% @books.each do |book| %>
      <li>- <%= link_to book.name, book_path(book) %> by <%= book.author.name %></li>
    <% end %>
  <% else %>
    <li>No books found in this category</li>
  <% end %>
</ul>