config/routes.rb
Rails.application.routes.draw do
  get "borrow_requests/new"
  get "borrow_requests/create"
  get "comments/create"
  get "authors/index"
  get "authors/show"
  get "categories/index"
  get "categories/show"
  get "books/show"
  get "users/show"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home/index"
  get "signup", to: "registrations#new", as: "signup"
  post "registrations", to: "registrations#create"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"
  root "home#index"

  resources :users, only: %i(show)
  resources :books, only: %i(show)
  resources :categories, only: %i(index show)
  resources :authors, only: %i(index show)
  resources :books do
    resources :comments, only: %i(create)
    resources :borrow_requests, only: %i(new create)
  end
  resources :users do
    member do
      get "borrow_history"
    end
  end
  resources :borrow_requests, only: %i(destroy)
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="csrf-token" content="<%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body style= "background-color: #e9e9e9;">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Library</a>
    <div class="collapse navbar-collapse">
      <div class="navbar_ul">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Categories', categories_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Authors', authors_path, class: 'nav-link' %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <%= link_to "Hello, #{current_user.name}", user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', login_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Signup', signup_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    <% if flash[:notice] %>
      <div class="alert alert-success flash-message" id="flash_notice">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>